const data = [
    {
        id: 0,
        name: 'Château des Milandes',
        img: '/assets/images/c1.jpg',
        price: '6.980.000',
        region: 'Nouvelle-Aquitaine',
        departement: 'Dordogne',
        city: 'Sarlat',
        bedrooms: '18',
        bathrooms: '5',
        livingspace: '1200',
        area: '6',
        map: '/assets/maps/nouvelleaquitaine.png',
        located: 'South'
    },
    {
        id: 1,
        name: 'Château de Chenonceau',
        img: '/assets/images/c2.jpg',
        price: '25.980.000',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Chenonceau',
        bedrooms: '58',
        bathrooms: '15',
        livingspace: '2800',
        area: '10',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 2,
        name: 'Château de Parthey',
        img: '/assets/images/c3.jpg',
        price: '5.500.000',
        region: ' Bourgogne-F-C',
        departement: 'Jura',
        city: 'Choisey',
        bedrooms: '12',
        bathrooms: '3',
        livingspace: '1800',
        area: '8',
        map: '/assets/maps/bourgognefranchecomte.png',
        located: 'Centre'
    },
    {
        id: 3,
        name: 'Château d\'azay le Rideau',
        img: '/assets/images/c4.jpg',
        price: '11.890.500',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Azay le Rideau',
        bedrooms: '8',
        bathrooms: '4',
        livingspace: '2100',
        area: '18',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 4,
        name: 'Château de Chantilly',
        img: '/assets/images/c5.jpg',
        price: '19.800.000',
        region: 'Hauts-de-France',
        departement: 'Oise',
        city: 'Chantilly',
        bedrooms: '24',
        bathrooms: '8',
        livingspace: '2600',
        area: '6',
        map: '/assets/maps/hautsdefrance.png',
        located: 'North'
    },
    {
        id: 5,
        name: 'Château d\'Amboise',
        img: '/assets/images/c6.jpg',
        price: '7.569.500',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Amboise',
        bedrooms: '8',
        bathrooms: '3',
        livingspace: '1800',
        area: '9',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 6,
        name: 'château de Pierrefonds',
        img: '/assets/images/c7.jpg',
        price: '145.890.000',
        region: 'Hauts de France',
        departement: 'Oise',
        city: 'Pierrefonds',
        bedrooms: '48',
        bathrooms: '12',
        livingspace: '15000',
        area: '15000',
        map: '/assets/maps/hautsdefrance.png',
        located: 'South'
    },
    {
        id: 7,
        name: 'Château d\'Usse',
        img: '/assets/images/c8.jpg',
        price: '18.750.000',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Rigny-Ussé',
        bedrooms: '23',
        bathrooms: '6',
        livingspace: '4860',
        area: '2',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 8,
        name: 'Château de Fougères',
        img: '/assets/images/c9.jpg',
        price: '13.950.000',
        region: 'Bretagne',
        departement: 'Ille-et-Vilaine',
        city: 'Fougères',
        bedrooms: '12',
        bathrooms: '2',
        livingspace: '800',
        area: '2',
        map: '/assets/maps/bretagne.png',
        located: 'Centre'
    },
    {
        id: 9,
        name: 'Château de Carcassonne',
        img: '/assets/images/c10.jpg',
        price: 'Not for Sale',
        region: 'Occitanie',
        departement: 'Aude',
        city: 'Carcassonne',
        bedrooms: '24',
        bathrooms: '5',
        livingspace: '400',
        area: '3',
        map: '/assets/maps/occitanie.png',
        located: 'South'
    }

]

export default data


