const data = [
    {
        id: 0,
        name: 'Chateau des Milandes',
        img: '/assets/images/c1.jpg',
        price: '6.980.000',
        region: 'Nouvelle-Aquitaine',
        departement: 'Dordogne',
        city: 'Sarlat',
        bedrooms: '18',
        bathrooms: '5',
        livingspace: '1200',
        area: '6',
        map: '/assets/maps/nouvelleaquitaine.png',
        located: 'South'
    },
    {
        id: 1,
        name: 'Château de Chenonceau',
        img: '/assets/images/c2.jpg',
        price: '25.980.000',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Chenonceau',
        bedrooms: '58',
        bathrooms: '15',
        livingspace: '2800',
        area: '10',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 2,
        name: 'Château de Parthey',
        img: '/assets/images/c3.jpg',
        price: '5.500.000',
        region: ' Bourgogne-F-C',
        departement: 'Jura',
        city: 'Choisey',
        bedrooms: '18',
        bathrooms: '3',
        livingspace: '1800',
        area: '8',
        map: '/assets/maps/bourgognefranchecomte.png',
        located: 'Centre'
    },
    {
        id: 3,
        name: 'Château d\'azay le Rideau',
        img: '/assets/images/c4.jpg',
        price: '11.890.500',
        region: 'Centre-Val de Loire',
        departement: 'Indre-et-Loire',
        city: 'Azay le Rideau',
        bedrooms: '18',
        bathrooms: '4',
        livingspace: '2100',
        area: '18',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 4,
        name: '',
        img: '/assets/images/c1.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/nouvelleaquitaine.png',
        located: 'South'
    },
    {
        id: 5,
        name: '',
        img: '/assets/images/c2.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 6,
        name: '',
        img: '/assets/images/c1.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/nouvelleaquitaine.png',
        located: 'South'
    },
    {
        id: 7,
        name: '',
        img: '/assets/images/c2.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 8,
        name: '',
        img: '/assets/images/c1.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/nouvelleaquitaine.png',
        located: 'South'
    },
    {
        id: 9,
        name: '',
        img: '/assets/images/c2.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 10,
        name: '',
        img: '/assets/images/c2.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 11,
        name: '',
        img: '/assets/images/c1.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/provence.png',
        located: 'South'
    },
    {
        id: 12,
        name: '',
        img: '/assets/images/c2.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/centrevaldeloire.png',
        located: 'Centre'
    },
    {
        id: 13,
        name: '',
        img: '/assets/images/c1.jpg',
        price: '',
        region: '',
        departement: '',
        city: '',
        bedrooms: '',
        bathrooms: '',
        livingspace: '',
        area: '',
        map: '/assets/maps/occitanie.png',
        located: 'South'
    },
    
]

export default data
     
    
